//! DexKit's existing FBS string slots carry MUTF-8, not UTF-8.
//! Never create a Rust str from those bytes before decoding.
use planus::{
    errors::ErrorKind, Builder, Cursor, Offset, SliceWithStartOffset, TableRead, VectorReadInner,
    VectorWrite, WriteAs, WriteAsOffset, WriteAsOptional, WriteAsPrimitive,
};
use std::mem::MaybeUninit;

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum EncodingError {
    #[error("Malformed DEX MUTF-8 string")]
    Malformed,
    #[error("Isolated UTF-16 surrogates are not supported by this API")]
    IsolatedSurrogate,
}

pub fn encode(text: &str) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(text.len());
    for unit in text.encode_utf16() {
        match unit {
            1..=0x7f => bytes.push(unit as u8),
            0..=0x7ff => {
                bytes.push(0xc0 | (unit >> 6) as u8);
                bytes.push(0x80 | (unit & 0x3f) as u8);
            }
            _ => {
                bytes.push(0xe0 | (unit >> 12) as u8);
                bytes.push(0x80 | ((unit >> 6) & 0x3f) as u8);
                bytes.push(0x80 | (unit & 0x3f) as u8);
            }
        }
    }
    bytes
}

pub fn decode(bytes: &[u8]) -> Result<String, EncodingError> {
    let mut units = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        let first = bytes[i];
        let (length, mut value, minimum) = match first {
            1..=0x7f => (1, u16::from(first), 0),
            0xc0..=0xdf => (2, u16::from(first & 31), 0x80),
            0xe0..=0xef => (3, u16::from(first & 15), 0x800),
            _ => return Err(EncodingError::Malformed),
        };
        let sequence = bytes.get(i..i + length).ok_or(EncodingError::Malformed)?;
        for &tail in &sequence[1..] {
            if tail & 0xc0 != 0x80 {
                return Err(EncodingError::Malformed);
            }
            value = (value << 6) | u16::from(tail & 63);
        }
        if value < minimum && !(length == 2 && value == 0) {
            return Err(EncodingError::Malformed);
        }
        units.push(value);
        i += length;
    }
    String::from_utf16(&units).map_err(|_| EncodingError::IsolatedSurrogate)
}

// Private wire types are byte-preserving. Conversion to the public DTO is
// explicitly fallible, including when a native result has a lone surrogate.
#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    serde::Serialize,
    serde::Deserialize,
)]
pub struct WireString(Vec<u8>);

impl WireString {
    pub fn mutf8(text: impl AsRef<str>) -> Self {
        Self(encode(text.as_ref()))
    }
    pub fn utf8(text: impl AsRef<str>) -> Self {
        Self(text.as_ref().as_bytes().to_vec())
    }
    pub fn decode(&self) -> Result<String, EncodingError> {
        decode(&self.0)
    }
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

#[repr(transparent)]
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct WireStr([u8]);
impl WireStr {
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}
impl From<&WireStr> for WireString {
    fn from(s: &WireStr) -> Self {
        Self(s.0.to_vec())
    }
}

impl<'a> TableRead<'a> for &'a WireStr {
    fn from_buffer(buffer: SliceWithStartOffset<'a>, offset: usize) -> Result<Self, ErrorKind> {
        let bytes = <&[u8]>::from_buffer(buffer, offset)?;
        let start = offset
            .checked_add(u32::from_buffer(buffer, offset)? as usize)
            .and_then(|n| n.checked_add(4))
            .ok_or(ErrorKind::InvalidOffset)?;
        let end = start
            .checked_add(bytes.len())
            .ok_or(ErrorKind::InvalidLength)?;
        if buffer.as_slice().get(end) != Some(&0) {
            return Err(ErrorKind::MissingNullTerminator);
        }
        // SAFETY: WireStr is a transparent wrapper of [u8], with no additional
        // validity invariant. The slice is bounds checked and borrows buffer.
        Ok(unsafe { &*(bytes as *const [u8] as *const WireStr) })
    }
}
impl<'a> VectorReadInner<'a> for &'a WireStr {
    type Error = planus::Error;
    const STRIDE: usize = 4;
    unsafe fn from_buffer(buffer: SliceWithStartOffset<'a>, offset: usize) -> planus::Result<Self> {
        TableRead::from_buffer(buffer, offset).map_err(|e: ErrorKind| {
            e.with_error_location("WireStr", "read", buffer.offset_from_start)
        })
    }
}
impl WriteAsOffset<WireStr> for WireString {
    fn prepare(&self, builder: &mut Builder) -> Offset<WireStr> {
        let length = u32::try_from(self.0.len()).expect("FBS string length");
        let size = self.0.len().checked_add(5).expect("FBS string size");
        // This is the standard FBS string scalar layout (length, bytes, NUL).
        // Table/vtable/vector/union layout remains generated by Planus.
        // SAFETY: every one of size bytes is initialized in the closure.
        unsafe {
            builder.write_with(size, 3, |_, out| {
                for (slot, byte) in out.iter_mut().zip(
                    length
                        .to_le_bytes()
                        .into_iter()
                        .chain(self.0.iter().copied())
                        .chain([0]),
                ) {
                    slot.write(byte);
                }
            });
        }
        builder.current_offset()
    }
}
impl WriteAs<Offset<WireStr>> for WireString {
    type Prepared = Offset<WireStr>;
    fn prepare(&self, builder: &mut Builder) -> Self::Prepared {
        WriteAsOffset::prepare(self, builder)
    }
}
impl WriteAsOptional<Offset<WireStr>> for WireString {
    type Prepared = Offset<WireStr>;
    fn prepare(&self, builder: &mut Builder) -> Option<Self::Prepared> {
        Some(WriteAsOffset::prepare(self, builder))
    }
}
// SAFETY: initializes the four bytes of every generated offset.
unsafe impl VectorWrite<Offset<WireStr>> for WireString {
    type Value = Offset<WireStr>;
    const STRIDE: usize = 4;
    fn prepare(&self, builder: &mut Builder) -> Self::Value {
        WriteAsOffset::prepare(self, builder)
    }
    unsafe fn write_values(values: &[Self::Value], bytes: *mut MaybeUninit<u8>, position: u32) {
        for (i, value) in values.iter().enumerate() {
            value.write(
                Cursor::new(&mut *bytes.add(i * 4).cast::<[MaybeUninit<u8>; 4]>()),
                position - (i * 4) as u32,
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn roundtrip_and_invalid_boundaries() {
        for text in [
            "",
            "ascii",
            "\u{0}",
            "\u{7ff}\u{800}\u{ffff}",
            "\u{1f600}\u{10ffff}",
        ] {
            assert_eq!(decode(&encode(text)).unwrap(), text);
        }
        assert_eq!(encode("\0"), [0xc0, 0x80]);
        assert_eq!(encode("\u{1f600}"), [0xed, 0xa0, 0xbd, 0xed, 0xb8, 0x80]);
        assert_eq!(
            decode(&[0xed, 0xa0, 0x80]),
            Err(EncodingError::IsolatedSurrogate)
        );
        for bytes in [
            &[0][..],
            &[0xc1, 0x81],
            &[0xe0, 0x81, 0x81],
            &[0xc0],
            &[0xf0, 0x9f, 0x98, 0x80],
        ] {
            assert_eq!(decode(bytes), Err(EncodingError::Malformed));
        }
    }
}
